name: 'Run lessons every 45 mins'
run-name: Your hack is running! Click me to see it's progress.

on:
  workflow_dispatch:
    inputs:
      lessonsToComplete:
        description: 'Amount of fake lessons to complete each time. (Each give 200 XP)'
        required: true
        default: 2

  schedule:
    - cron: '0 8,10,12,14,17,20 * * *'

jobs:
  check-bats-version:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4


      - uses: actions/setup-node@v4
        with:
          node-version: '20'
        
      - run: npm install node-fetch

      - run: npm run xp
        env:
          lessonsToComplete: ${{ github.event.inputs.lessonsToComplete }}
          token: ${{ secrets.TOKEN }}
          userId: ${{ secrets.USER_ID }}
